# Generated by Django 3.2.9 on 2021-11-25 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passwrod',
            new_name='password',
        ),
    ]
