# Generated by Django 3.2.9 on 2021-11-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0005_auto_20211128_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
