# Generated by Django 3.2.9 on 2021-11-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0007_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='ranged',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
