# Generated by Django 3.2.9 on 2021-12-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0008_alter_registration_ranged'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageViewsCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=150, unique=True)),
                ('counter', models.IntegerField(default=0)),
            ],
        ),
    ]
