# Generated by Django 3.2.9 on 2022-02-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0010_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='eid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
