# Generated by Django 3.2.9 on 2022-02-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0011_auto_20220215_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='econtact',
            field=models.IntegerField(max_length=15),
        ),
    ]
