# Generated by Django 3.2.9 on 2022-02-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0012_alter_employee_econtact'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='eaddress',
            field=models.CharField(default='Delhi', max_length=50),
        ),
    ]
